name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

evn:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
       matrix:
            node-version: [18.x]

    steps:
      - uses: actions/checkout@v6
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.noda-version }}
          cache: 'npm'
      - name: Setup
        run: make setup

      - name: Linter
        run: make lint

      - name: Test
        run: make test

      - name: My action
      - uses: hexlet-components/hello-from-hexlet-action
